import './globals.css'



export const metadata = {
  title: 'Prince React',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressContentEditableWarning>{children}</body>
    </html>
  )
}
